name: spotify_webapp
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  go_router: ^6.0.1
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  flutter:
    sdk: flutter

  # Custom Packages
  auth:
    path: packages/auth
  core:
    path: packages/core
  ui:
    path: packages/ui
  routing:
    path: packages/routing

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
