name: routing
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # Freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  flutter_bloc: ^8.1.1
  go_router: ^6.0.1

  flutter:
    sdk: flutter
  
  # Custom Packages
  core:
    path: ../core

dev_dependencies:
  # Freezed
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
