include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# To Work with freezed
analyzer:
  errors:
    invalid_annotation_target: ignore
