name: ui
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_svg: ^1.1.6
  go_router: ^6.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: SpotifyCircular
      fonts:
        - asset: assets/fonts/spotify_circular/CircularStd-Black.otf
          weight: 900
        - asset: assets/fonts/spotify_circular/CircularStd-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/spotify_circular/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/spotify_circular/CircularStd-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/spotify_circular/CircularStd-Book.otf
        - asset: assets/fonts/spotify_circular/CircularStd-BookItalic.otf
          style: italic
        - asset: assets/fonts/spotify_circular/CircularStd-Light Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/spotify_circular/CircularStd-Light.otf
          weight: 300
        - asset: assets/fonts/spotify_circular/CircularStd-Medium.otf
          weight: 500
        - asset: assets/fonts/spotify_circular/CircularStd-MediumItalic.otf
          weight: 500
          style: italic
